"""initial

Revision ID: 186c00fe3a5c
Revises: 
Create Date: 2024-01-29 11:34:50.975747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '186c00fe3a5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('info',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('contacts', sa.String(), nullable=True),
    sa.Column('links_first', sa.String(), nullable=True),
    sa.Column('links_second', sa.String(), nullable=True),
    sa.Column('links_third', sa.String(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('updated_notif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('result', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('pay_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pay_forever', sa.Boolean(), nullable=False),
    sa.Column('completed', postgresql.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    variables = op.create_table('variables',
    sa.Column('name', sa.Enum('ADVERT', 'LIMIT', 'GOAL', name='varsenum'), nullable=False),
    sa.Column('str_value', sa.String(), nullable=True),
    sa.Column('int_value', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('content_type', sa.Enum('ANIMATION', 'MESSAGE', 'PHOTO', 'VIDEO', name='contenttypes'), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###
    op.bulk_insert(variables, [
        {
            "name": "ADVERT",
            "str_value": None,
            "int_value": None,
            "file_id": None,
            "content_type": None
        },
        {
            "name": "LIMIT",
            "str_value": None,
            "int_value": 5,
            "file_id": None,
            "content_type": None
        },
        {
            "name": "GOAL",
            "str_value": None,
            "int_value": 0,
            "file_id": None,
            "content_type": "MESSAGE"
        },
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variables')
    op.drop_table('users')
    op.drop_table('queries')
    op.drop_table('payments')
    op.drop_table('info')
    op.drop_table('channels')
    # ### end Alembic commands ###
